version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"

#  nginx:
#    restart: always
#    build: ./nginx/
#    ports:
#      - "80:80"
#    volumes:
#      - /www/public
#    volumes_from:
#      - web
#    links:
#      - web:web