# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f1f1ebd462a209ed90c402a0318b07d699790fb77ac7dac0f9b7967356352b2959c6e82b0060b2406524354357bf31abfe5b21d629e96426caabac35d919a6d

test:
  secret_key_base: 3db43a26a571ce3d526db9bd9746e52c064895459f82feb90701f7854f2170bd8f51d39303cd01845956327cc1f3b555495f1b9714165e2db7a570fd9da9a1b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
